name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        echo 'export PATH="/usr/local/heroku/bin:$PATH"' >> $GITHUB_ENV
      shell: bash

    - name: Login to Heroku CLI
      run: |
        expect -c '
        spawn heroku login -i
        expect "Email:" { send "$env(HEROKU_EMAIL)\r" }
        expect "Password:" { send "$env(HEROKU_API_KEY)\r" }
        expect eof'
      env:
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}


    - name: Log in to Heroku Container Registry
      run: |
        docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push Docker image
      run: |
        docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Set Heroku Environment Variables
      run: |
        heroku config:set HEROKU_EMAIL=${{ secrets.HEROKU_EMAIL }} HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} HEROKU_APP_NAME=${{ secrets.HEROKU_APP_NAME }} -a ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Release to Heroku
      run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
